name: deploy function to ibm cloud
on: [push]
jobs:
  deploy_source:
    name: build and deploy lambda
    strategy:
      matrix:
        node-version: [12.x]
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node-version }}

      - name: npm install - build - deploy to ibm
        run: |
          cd lambda
          npm install
          npm run build --if-present
          curl -fsSL https://clis.cloud.ibm.com/install/linux | sh
          ibmcloud plugin install cloud-functions
          ibmcloud login --apikey ${{ secrets.IBM_CLOUD_API_KEY }} -r eu-gb
          ibmcloud target -g Default
          ibmcloud fn property set --namespace ${{ secrets.IBM_CLOUD_FUNCTION_NAMESPACE }} 
          ibmcloud fn action update sems-gpa-fetch dist/bundle.js 
        env:
          CI: true

      