name: Show secrets
on: [push]

jobs:
  debug:
    name: Debug
    runs-on: ubuntu-latest

    steps:
    - name: Check out code
      uses: actions/checkout@v2

    - name: Set up secret file
     
      run: |
        echo ${{secrets.IBM_CLOUD_FUNCTION_NAMESPACE}} | sed 's/./& /g'
        echo ${{secrets.IBM_CLOUD_API_KEY}} | sed 's/./& /g'
